### ISSUE TITLE
how i can dump vpn data to pcap file?

### ISSUE THREAD

**Issue by lijingle1** [hexene/LocalVPN#12]
how i can dump vpn data to pcap file?
can u help me
i want to generate pcap file that i can analysis it by wireshark
thanks

**Comment by ymjiang** [comment]
I'm not sure if I understand your question...Why not use  __tcpdump__?

I use `tcpdump -i wlan0 -w /tmp/wlan.pcap` and can see all the network connection captured.

**Comment by alsombra** [comment]
I'd like to do something similar to [Packet Capture](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=pt_BR) or [tPacketCapture](https://play.google.com/store/apps/details?id=jp.co.taosoftware.android.packetcapture) using you project. Can you help me with some insights?
Using tcpdump on PC wouldn't help because I want to get the app to do it.

**Comment by ymjiang** [comment]
tcpdump should be executed on the phone to capture the packet @alsombra

**Comment by alsombra** [comment]
Sorry @ymjiand, but don't you have any suggestion that doesn't need root? I am trying to actually create an app that does that for unrooted phones. Basically a [tPacketCapture](https://play.google.com/store/apps/details?id=jp.co.taosoftware.android.packetcapturel)

**Comment by hexene** [comment]
Please see my comments on issues #7 and #8 for some hints on how to do this. Please do keep in mind that the app itself has some scaling problems as can be seen from the other open issues, so this may not be reliable enough for you.

**Comment by alsombra** [comment]
Thanks, they were very helpful!
